# 基本設定
output:
  directory: "./output"
  formats: ["json", "txt"]

# 音声認識設定
speech_recognition:
  language: "ja"
  engine: "whisper"
  whisper_model: "large-v3"  # 単語レベルのタイムスタンプ対応モデル
  min_confidence: 0.7
  temperature: 0.0
  beam_size: 5

# スクリーンショット設定
screenshot:
  interval: 5  # 秒単位
  format: "png"
  quality: 85

# OCR設定
ocr:
  languages: "jpn+eng"
  config: "--psm 6 --oem 3 -c tessedit_char_whitelist=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをんアイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン・ー"
  page_seg_mode: 6  # 単一の均一なテキストブロックとして処理

# ログ設定
logging:
  level: "INFO"
  max_files: 7